### ISSUE TITLE
Example of settings changes

### ISSUE THREAD

**Issue by kaktucs** [tomjnixon/mk2.py#5]
Hello, I have Easy Solar 24/1600/50 connected to the grid in UPS mode, I can't use ESS for legal reason. Can you provide an example of settings change? Sometimes I am charging the battery from the grid and I use VEconfigure 3 to enable and disable charger also changing the virtual switch to ignore AC input depend on battery voltage to get pass-through mode active . I now a little bit python but doesn't understand how to use your project. Thanks you.

**Comment by tomjnixon** [comment]
Hi,

Thanks for having a look, i've added an example which can write ram vars, settings and flags, see the README.

I do a the same thing, so the examples in the README should be what you're after.

There's quite a lot of code in the write example, but really all you need to write a setting is something like monitor.py changed to:

```py
# open serial port, interface and session as in monitor.py, then...
async with interface.run(), session.run():
    await session.write_setting(Setting.VS_USAGE, 0)
```

I'll try to get around to writing some more documentation for this kind of thing.

**Comment by tomjnixon** [comment]
Also, please let me know how you get on, and re-open this if you have issues.

**Comment by kaktucs** [comment]
i check what version of python running on venus os and it is python 3.8, sadly cant run it directly on venus os. Cant run on my computer as well ubuntu 22.04 last version in repository is 3.10. 
On python 3.10 i have this error after install:

> /usr/bin/python: Error while finding module specification for 'mk2.examples.write' (ModuleNotFoundError: No module named 'mk2')

I give up for today :)

**Comment by tomjnixon** [comment]
Ah ok, bad luck.

I don't really want to support old versions, because some of the new features in the asyncio and enum modules are useful. Sorry.

It's probably possible to do this with the victron DBus API (i.e. using the MK2 to dbus converter built into venus OS). I'd try monitoring the DBus traffic while changing settings in VictronConnect (no idea how to do that though, sorry again).
